[metadata]
        name = "boxo-performance-test"

[global]
        plan = "response-time-based"
        case = "constant-latency_third-peer-joined-to-session-after-500-blocks"
        total_instances = 4
        builder = "docker:go"
        runner = "local:docker"

[global.build_config]
        push_registry=false

[global.run.test_params]
        size      = "1MB"
        block_count     = "100"
	provider_count	= "3"

[[groups]]
        id = "early_provider"
        instances = { count = 2 }
        [groups.resources]
                memory = "4096Mi"
                cpu = "1000m"

[[groups]]
        id = "late_provider"
        instances = { count = 1 }
        [groups.resources]
                memory = "4096Mi"
                cpu = "1000m"

[[groups]]
        id = "requester"
        instances = { count = 1 }
        [groups.resources]
                memory = "4096Mi"
                cpu = "1000m"
