[metadata]
        name = "boxo-performance-test"

[global]
        plan = "response-time-based"
        case = "constant-latency_all-peers-joined-to-session-at-the-beginning"
        total_instances = 3
        builder = "docker:go"
        runner = "local:docker"

[global.build_config]
        push_registry=false

[global.run.test_params]
        size      = "1MB"
        block_count     = "10"
	provider_count	= "2"

[[groups]]
        id = "early_provider"
        instances = { count = 2 }
        [groups.resources]
                memory = "4096Mi"
                cpu = "1000m"

[[groups]]
        id = "requester"
        instances = { count = 1 }
        [groups.resources]
                memory = "4096Mi"
                cpu = "1000m"
