[metadata]
        name = "boxo-performance-test"

[global]
        plan = "response-time-based"
        case = "variable-latency" // 3rd peer's latency increases to 90ms
        total_instances = 11
        builder = "docker:go"
        runner = "local:docker"

[global.build_config]
        push_registry=false

[global.run.test_params]
        size      = "1MB"
        block_count     = "100"
	provider_count	= "3"

[[groups]]
        id = "early_provider"
        instances = { count = 3 }
        [groups.resources]
                memory = "4096Mi"
                cpu = "1000m"

[[groups]]
        id = "requester"
        instances = { count = 1 }
        [groups.resources]
                memory = "4096Mi"
                cpu = "1000m"
