name = "response-time-based"

[builders."docker:go"]
        enabled = true
        go_version = "1.20"
        build_base_image       = "golang:1.20-alpine"

[runners."local:docker"]
        enabled = true

[[testcases]]
        name= "constant-latency_all-peers-joined-to-session-at-the-beginning"
        instances = { min = 4, max = 100, default = 4 }

        [testcases.params]
        size = { type = "int", desc = "size of file to transfer, in human-friendly form", default = "1MiB" }
        count = { type = "int", desc = "number of transfers", default = "100" }

[[testcases]]
        name= "constant-latency_third-peer-joined-to-session-after-500-blocks"
        instances = { min = 4, max = 100, default = 4 }

        [testcases.params]
        size = { type = "int", desc = "size of file to transfer, in human-friendly form", default = "1MiB" }
        count = { type = "int", desc = "number of transfers", default = "100" }

[[testcases]]
        name= "variable-latency"
        instances = { min = 4, max = 100, default = 4 }

        [testcases.params]
        size = { type = "int", desc = "size of file to transfer, in human-friendly form", default = "1MiB" }
        count = { type = "int", desc = "number of transfers", default = "100" }
